### PR TITLE
Vantiv (Litle): Add scrubbing

### PR DESCRIPTION
**Pull request by szymoniwacz**
Adds ability to log Raw Log Contents in Raw Gateway Log.

### CODE REVIEW

**Comment by szymoniwacz** [comment]
Tested on staging and raw gateway log is saved:
Screenshot 2019-06-13 at 14 07 52

But question is, do we want to scrub `litleToken` from Raw Content Log?

**Comment by wsmoak** [comment]
Isn't that our `vault_token`?   (View the payment profile with AnyRecordFinder and confirm.)

If so, it doesn't need to be hidden.  

It does _look_ like a credit card number and I think we have been concerned about this in the past, *especially* because they send the last-4 of the card number back in the token, but it is "just" a token like the others, for example cus_F1uraXhPshHYNY from Stripe.

**Comment by wsmoak** [comment]
What about the `<expDate>0435</expDate>` -- do we filter that for other gateways or is it okay?

**Comment by szymoniwacz** [comment]
Yes, it is `vault_token` in payment profile.

You're right, last 4 numbers of token are the same as last 4 numbers of credit card number, but rest is different.
I haven't found filtering of `expDate` (or anything that looks like it) in any of gateways in ActiveMerchant.

**Pull request merged**
