### PR TITLE
[DigitalRiver] Update to newest DR API version changes

### PR DESCRIPTION
**Pull request by pohor**
This PR adds updates to handle the most recent changes to the DigitalRiver API and updates to the digital_river gem version that handles the new API.

### CODE REVIEW

**Comment by pohor** [comment]
Screenshot 2021-06-21 at 17 00 08
Local test suite

**Review by dbackowski — DISMISSED** [review]
Looks good! 🚀

**Comment by pohor** [comment]
Screenshot 2021-06-23 at 13 06 26
local test run

**Review by dbackowski — APPROVED** [review]
🚢

**Pull request merged**
