### PR TITLE
Add eway error codes

### PR DESCRIPTION
**Pull request by mwhagedorn**
Fixes: https://github.com/chargify/chargify/issues/6301

Since our custom eway gateway impl is a little outdated, it didnt have the latest error codes from the gateway.   This change just adds those in.

### CODE REVIEW

**Comment by drewblas** [comment]
FWIW, Instead of manually trying to add all your personal gitignores to every project, you might like to try creating a `~/.gitignore_global` file

Here's an example of mine
[gitignore_global.txt](https://github.com/chargify/active_merchant/files/868943/gitignore_global.txt)

**Comment by mwhagedorn** [comment]
@drewblas thank you that is cool

**Comment by drewblas** [comment]
I approved this, but then got to re-thinking does this negatively impact our ability to continue updating off the latest active_merchant official gem?  I thought we had set up a different way of doing these changes such that we won't later have merge conflicts.  This seems highly likely to cause later merge conflicts

**Comment by wsmoak** [comment]
This is our custom (legacy, deprecated,) implementation of eWAY Rapid, so there is no conflict.

**Pull request merged**
